// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG1vHAkMEKt3AMDlaDLIs8UoI9tvMH17I',
    appId: '1:112764171788:web:830d7e2b50dc1e64f46029',
    messagingSenderId: '112764171788',
    projectId: 'bookbutler-dfb30',
    authDomain: 'bookbutler-dfb30.firebaseapp.com',
    storageBucket: 'bookbutler-dfb30.firebasestorage.app',
    measurementId: 'G-70XMNP9FZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaWYIiS61CkrOFmF6X0aR822YBT_sWOJQ',
    appId: '1:112764171788:android:1241ac6c5ed0f9dbf46029',
    messagingSenderId: '112764171788',
    projectId: 'bookbutler-dfb30',
    storageBucket: 'bookbutler-dfb30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Cyu6j165qK6FUuYZ--XZYsS9G2QC-KQ',
    appId: '1:112764171788:ios:2ad33343a19b347ff46029',
    messagingSenderId: '112764171788',
    projectId: 'bookbutler-dfb30',
    storageBucket: 'bookbutler-dfb30.firebasestorage.app',
    iosBundleId: 'com.example.projectThera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0Cyu6j165qK6FUuYZ--XZYsS9G2QC-KQ',
    appId: '1:112764171788:ios:2ad33343a19b347ff46029',
    messagingSenderId: '112764171788',
    projectId: 'bookbutler-dfb30',
    storageBucket: 'bookbutler-dfb30.firebasestorage.app',
    iosBundleId: 'com.example.projectThera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG1vHAkMEKt3AMDlaDLIs8UoI9tvMH17I',
    appId: '1:112764171788:web:969c083e1a40942ef46029',
    messagingSenderId: '112764171788',
    projectId: 'bookbutler-dfb30',
    authDomain: 'bookbutler-dfb30.firebaseapp.com',
    storageBucket: 'bookbutler-dfb30.firebasestorage.app',
    measurementId: 'G-4MPKXNVSKC',
  );
}
