import { useState } from "react";
import { Share2, Copy, Check, Sparkles, Download } from "lucide-react";
import { Button } from "./ui/button";
import { Card } from "./ui/card";
import { Textarea } from "./ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./ui/tabs";
import { Badge } from "./ui/badge";

interface SocialContentProps {
  bookTitle: string;
  author: string;
  bookCover: string;
  progress: number;
  quote?: string;
  userNotes?: string;
}

export function SocialContent({
  bookTitle,
  author,
  bookCover,
  progress,
  quote,
  userNotes,
}: SocialContentProps) {
  const [copied, setCopied] = useState(false);
  const [generatedTweet, setGeneratedTweet] = useState("");
  const [generatedThread, setGeneratedThread] = useState<string[]>([]);

  const handleGenerateTweet = () => {
    const tweet = `📚 Currently ${progress}% through "${bookTitle}" by ${author}\n\n${
      quote || "An incredible journey so far!"
    }\n\n#ReadingCommunity #Books`;
    setGeneratedTweet(tweet);
  };

  const handleGenerateThread = () => {
    const thread = [
      `📚 Just finished reading "${bookTitle}" by ${author}\n\nHere are my key takeaways 🧵`,
      `1/ The most powerful insight: ${quote || "This book challenged my perspective on life and growth."}`,
      `2/ ${userNotes || "The author's writing style is captivating, making complex ideas accessible and engaging."}`,
      `3/ If you're interested in personal growth and mindful living, this is a must-read.\n\nHighly recommend! ⭐⭐⭐⭐⭐`,
    ];
    setGeneratedThread(thread);
  };

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-4 p-4">
      <div>
        <h2 className="text-xl font-semibold text-gray-900 mb-1">Share Your Journey</h2>
        <p className="text-sm text-gray-600">The Butler will draft your social content</p>
      </div>

      {/* Share Card Preview */}
      <Card className="overflow-hidden">
        <div className="relative">
          <img src={bookCover} alt={bookTitle} className="w-full h-48 object-cover" />
          <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/40 to-transparent" />
          <div className="absolute bottom-4 left-4 right-4 text-white">
            <h3 className="font-bold text-lg mb-1">{bookTitle}</h3>
            <p className="text-sm opacity-90 mb-2">{author}</p>
            <div className="flex items-center gap-3">
              <div className="flex-1 bg-white/20 rounded-full h-2">
                <div
                  className="bg-white h-2 rounded-full transition-all"
                  style={{ width: `${progress}%` }}
                />
              </div>
              <span className="text-sm font-semibold">{progress}%</span>
            </div>
          </div>
        </div>
        <div className="p-4 bg-gradient-to-br from-indigo-50 to-purple-50">
          <p className="text-sm italic text-gray-700">
            "{quote || "An engaging read that offers fresh perspectives."}"
          </p>
          <div className="flex items-center justify-between mt-3">
            <span className="text-xs text-gray-600">Generated by The Butler</span>
            <Badge variant="secondary" className="text-xs">Ready to Share</Badge>
          </div>
        </div>
      </Card>

      <Button className="w-full" variant="outline">
        <Download className="size-4 mr-2" />
        Download Share Card
      </Button>

      {/* Content Tabs */}
      <Tabs defaultValue="tweet">
        <TabsList className="grid w-full grid-cols-2">
          <TabsTrigger value="tweet">Single Post</TabsTrigger>
          <TabsTrigger value="thread">Thread</TabsTrigger>
        </TabsList>

        <TabsContent value="tweet" className="space-y-3 mt-4">
          <Button
            onClick={handleGenerateTweet}
            className="w-full"
            disabled={!!generatedTweet}
          >
            <Sparkles className="size-4 mr-2" />
            {generatedTweet ? "Tweet Generated" : "Generate Tweet"}
          </Button>

          {generatedTweet && (
            <Card className="p-4">
              <Textarea
                value={generatedTweet}
                onChange={(e) => setGeneratedTweet(e.target.value)}
                rows={6}
                className="mb-3"
              />
              <div className="flex gap-2">
                <Button
                  onClick={() => handleCopy(generatedTweet)}
                  variant="outline"
                  className="flex-1"
                >
                  {copied ? (
                    <>
                      <Check className="size-4 mr-2" />
                      Copied!
                    </>
                  ) : (
                    <>
                      <Copy className="size-4 mr-2" />
                      Copy
                    </>
                  )}
                </Button>
                <Button className="flex-1">
                  <Share2 className="size-4 mr-2" />
                  Share
                </Button>
              </div>
            </Card>
          )}
        </TabsContent>

        <TabsContent value="thread" className="space-y-3 mt-4">
          <Button
            onClick={handleGenerateThread}
            className="w-full"
            disabled={generatedThread.length > 0}
          >
            <Sparkles className="size-4 mr-2" />
            {generatedThread.length > 0 ? "Thread Generated" : "Generate Thread"}
          </Button>

          {generatedThread.length > 0 && (
            <div className="space-y-3">
              {generatedThread.map((tweet, index) => (
                <Card key={index} className="p-4">
                  <div className="flex items-start gap-2 mb-2">
                    <Badge variant="secondary">{index + 1}</Badge>
                    <span className="text-xs text-gray-500">Tweet {index + 1}/{generatedThread.length}</span>
                  </div>
                  <Textarea
                    value={tweet}
                    onChange={(e) => {
                      const newThread = [...generatedThread];
                      newThread[index] = e.target.value;
                      setGeneratedThread(newThread);
                    }}
                    rows={4}
                  />
                </Card>
              ))}
              <div className="flex gap-2">
                <Button
                  onClick={() => handleCopy(generatedThread.join("\n\n"))}
                  variant="outline"
                  className="flex-1"
                >
                  {copied ? (
                    <>
                      <Check className="size-4 mr-2" />
                      Copied!
                    </>
                  ) : (
                    <>
                      <Copy className="size-4 mr-2" />
                      Copy All
                    </>
                  )}
                </Button>
                <Button className="flex-1">
                  <Share2 className="size-4 mr-2" />
                  Share Thread
                </Button>
              </div>
            </div>
          )}
        </TabsContent>
      </Tabs>

      {/* Butler's Note */}
      <Card className="p-3 bg-indigo-50 border-indigo-200">
        <p className="text-sm text-indigo-900">
          <span className="font-semibold">🎩 The Butler suggests:</span> Your reading notes contain excellent material for a compelling thread. Shall I emphasize the themes of resilience and growth?
        </p>
      </Card>
    </div>
  );
}
